/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Jupiter.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere001_1.geometry}
        material={materials['02___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere001_1_1.geometry}
        material={materials['07___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere001_1_2.geometry}
        material={materials['03___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere001_1_3.geometry}
        material={materials['08___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere001_1_4.geometry}
        material={materials['01___Default']}
      />
    </group>
  )
}

useGLTF.preload('/Jupiter.glb')
