/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: FoxVenture (https://sketchfab.com/FoxVenture)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-moon-d671eb35d2244c8cb98d06b4948d9937
Title: Low Poly Moon
*/

import  { useRef } from 'react'
import { useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei'

const Moon = (props) => {


  const { nodes, materials } = useGLTF('models/low_poly_moon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moon_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moon_Light_grey_middle_part_0.geometry}
        material={materials.Light_grey_middle_part}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moon_Shadow_Dark_0.geometry}
        material={materials.Shadow_Dark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moon_Shadow_Darkest_0.geometry}
        material={materials.Shadow_Darkest}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moon_Medium_Dark_0.geometry}
        material={materials.Medium_Dark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moon_lambert5_0.geometry}
        material={materials.lambert5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Moon_Main_colour_0.geometry}
        material={materials.Main_colour}
      />
    </group>
  )
}

useGLTF.preload('/models/low_poly_moon.glb')

export default Moon