/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Neptune.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere001_1.geometry}
        material={materials['05___Default']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.GeoSphere001_1_1.geometry}
        material={materials['04___Default']}
      />
    </group>
  )
}

useGLTF.preload('/Neptune.glb')